name: zaitoonpro
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+6

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.1
  dio: ^5.9.0
  printing: ^5.14.2
  flag: ^7.0.2
  font_awesome_flutter: ^11.0.0
  shamsi_date: ^1.1.1
  path_provider: ^2.1.5
  path: ^1.9.1
  file_selector: ^1.0.4
  file_picker: ^12.0.0-beta.7
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  image: ^4.5.4
  http: ^1.6.0
  pdf: ^3.11.3
  cached_network_image: ^3.4.1
  syncfusion_flutter_charts: ^33.2.15
  share_plus: ^13.3.0
  permission_handler: ^13.0.0
  universal_html: ^2.3.0
  syncfusion_flutter_xlsio: ^33.2.13
  window_manager: ^0.5.1
  shimmer: ^3.0.0
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf

    - family: NotoNaskh
      fonts:
        - asset: assets/fonts/NotoNaskh/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskh/NotoNaskhArabic-Bold.ttf
        - asset: assets/fonts/NotoNaskh/NotoNaskhArabic-SemiBold.ttf
        - asset: assets/fonts/NotoNaskh/NotoNaskhArabic-Medium.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf